#### This notebook is meant to be a high-level walkthrough of Python and some data science examples. We're working under the assumption you have installed Python, Anaconda, and are familiar with installing packages through pip or conda commands. This is not a tutorial on setting up Python interpreters, explaining what a for/while loop is, or efficiency of any of the following methods.

## Import Statements
We're going to start the top of any file we make with some import statements. Import statements tell Python what packages we're looking to use in our file. The basic structure of an import state is:

> import _Package Name_

However, if the package we're importing has a long name or you're going to be typing it a lot, you can add "as" to an import statement to shorten the name. This structure looks like:

> import _Package Name_ as _shorter name_

One final way to import packages is to reference a specific class in the package you're importing. An example of this structure is:

> from _Package Name_ import _Package Class_

An example of each type of importing are shown in the code block below.

In [688]:
import numpy
import matplotlib.pyplot as plt
from citrination_client import CitrinationClient

## Lists
Now that we've covered importing several libraries, we'll make some data to demonstrate some other capabilities of Python. First, we'll cover some operations with lists. Below we make a list containing the numbers from 0 to 99. We define the list in the first line using square brackets [] and add items to the list using the "append" method.

In [689]:
list = []
for i in range(0, 100):
    list.append(i)
print(list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In the cell above, we append items to the list using the 'append' method. There are many other list operations that can be performed and are explained in the docs (https://docs.python.org/3/tutorial/datastructures.html). We'll demonstrate several of them on our list below.

In [690]:
# Remove items from a list using remove
# Here, we remove every item in the list by going through list in reversed order.
for i in reversed(list):
    list.remove(i)
print(list)

[]


In [691]:
# We can also add items to a list when we create it:
gases = ["Neon", "Argon", "Helium"]
print(gases)

['Neon', 'Argon', 'Helium']


In [692]:
# And use "extend" to add items to a list
gases.extend(["Hydrogen", "Oxygen", "Nitrogen"])
print(gases)

['Neon', 'Argon', 'Helium', 'Hydrogen', 'Oxygen', 'Nitrogen']


In [693]:
# Check how many elements are in our list:
print(len(gases))

6


We can also access specific elements of our list by using square brackets [] and an index we'd like to access, or use a colon : inside the brackets to access all elements of a list up to a certain point.

In [694]:
print("Access element by index: " + str(gases[1]))
print("Access whole list: " + str(gases[:]))
print("Access first 3 elements: " + str(gases[:3]))
print("Access last 3 elements: " + str(gases[3:]))

Access element by index: Argon
Access whole list: ['Neon', 'Argon', 'Helium', 'Hydrogen', 'Oxygen', 'Nitrogen']
Access first 3 elements: ['Neon', 'Argon', 'Helium']
Access last 3 elements: ['Hydrogen', 'Oxygen', 'Nitrogen']


Again, all list operations can be found in https://docs.python.org/3/tutorial/datastructures.html.
One final note to make about lists is how copyting lists and changing elements works. Say, for example, you would like to copy the list of gases we made earlier and run some operations on it:

In [695]:
# Make a reference to the gases list we made early
elements = gases
print("Make another list called elements:")
print("elements: " + str(elements))
print("gases:    " + str(gases))
print()

# Remove something from elements.
elements.remove("Hydrogen")
print("Remove an item from elements:")
print("elements: " + str(elements))
print("gases:    " + str(gases))
print()

elements.extend(["Carbon", "Iron", "Tin"])
print("Add something to elements:")
print("elements: " + str(elements))
print("gases:    " + str(gases))

Make another list called elements:
elements: ['Neon', 'Argon', 'Helium', 'Hydrogen', 'Oxygen', 'Nitrogen']
gases:    ['Neon', 'Argon', 'Helium', 'Hydrogen', 'Oxygen', 'Nitrogen']

Remove an item from elements:
elements: ['Neon', 'Argon', 'Helium', 'Oxygen', 'Nitrogen']
gases:    ['Neon', 'Argon', 'Helium', 'Oxygen', 'Nitrogen']

Add something to elements:
elements: ['Neon', 'Argon', 'Helium', 'Oxygen', 'Nitrogen', 'Carbon', 'Iron', 'Tin']
gases:    ['Neon', 'Argon', 'Helium', 'Oxygen', 'Nitrogen', 'Carbon', 'Iron', 'Tin']


To prevent unwanted changes to the original array gases, we can use the .copy() method or get all indices of the original list using [:].

In [696]:
# Remake gases since we removed items from it in the previous cell.
gases = ["Neon", "Argon", "Helium", "Hydrogen", "Oxygen", "Nitrogen"]
elements = gases.copy()
print("Make another list called elements:")
print("elements: " + str(elements))
print("gases:    " + str(gases))
print()

# Remove something from elements.
elements.remove("Hydrogen")
print("Remove an item from elements:")
print("elements: " + str(elements))
print("gases:    " + str(gases))
print()

elements.extend(["Carbon", "Iron", "Tin"])
print("Add something to elements:")
print("elements: " + str(elements))
print("gases:    " + str(gases))

Make another list called elements:
elements: ['Neon', 'Argon', 'Helium', 'Hydrogen', 'Oxygen', 'Nitrogen']
gases:    ['Neon', 'Argon', 'Helium', 'Hydrogen', 'Oxygen', 'Nitrogen']

Remove an item from elements:
elements: ['Neon', 'Argon', 'Helium', 'Oxygen', 'Nitrogen']
gases:    ['Neon', 'Argon', 'Helium', 'Hydrogen', 'Oxygen', 'Nitrogen']

Add something to elements:
elements: ['Neon', 'Argon', 'Helium', 'Oxygen', 'Nitrogen', 'Carbon', 'Iron', 'Tin']
gases:    ['Neon', 'Argon', 'Helium', 'Hydrogen', 'Oxygen', 'Nitrogen']


## Numpy
Another way to deal with storing multiple items is to use the NumPy package and create NumPy arrays instead of lists. A good tutorial on all operations shown in this notebook and more are available at https://docs.scipy.org/doc/numpy/user/quickstart.html and https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.array-manipulation.html. 

To demonstrate some of NumPy's array capabilities, we'll make a 1D NumPy array containing the numbers from 0 to 9.

In [697]:
import numpy as np
a = np.array([0,1,2,3,4,5,6,7,8,9])
print("a: " + str(a))

a: [0 1 2 3 4 5 6 7 8 9]


In [698]:
# Or a less verbose way to make a NumPy array that's just a range of 10 numbers that starts at 0...
b  = np.arange(0,10)
print("b: " + str(b))

b: [0 1 2 3 4 5 6 7 8 9]


Just as with Python lists, NumPy arrays can be updated using methods such as insert(), append(), or concatenate() to update a 1D NumPy array or stack() to create an n-dimension NumPy array, or use delete() to remove elements. Each of these methods returns an updated NumPy array, so be sure to store the updated array in a variable.

Also note how these methods are called. Unlike Python lists where you call methods directly on an array, NumPy arrays are updated by calling a method that requires the NumPy array as an input.

In [699]:
# Insert the int 7 at position 4 in a
a_insert = np.insert(a, 4, 7)
print("Original a array: " + str(a))
print("Insert 3 into a:  " + str(a_insert))
print()

# Append
a_append = np.append(a, 10)
print("Original a array: " + str(a))
print("Append 10 into a: " + str(a_append))
print()

# Concatenate
a_concat = np.concatenate((a, b))
print("Original a array:    " + str(a))
print("Concatenate a and b: " + str(a_concat))
print()

# Stack
a_stack = np.stack((a, b))
print("Original a array: " + str(a))
print("Stack a and b:    " + str(a_stack))
print()

# Delete
a_delete = np.delete(a, [4])
print("Original a array: " + str(a))
print("Delete 4 from a:  " + str(a_delete))
print()

Original a array: [0 1 2 3 4 5 6 7 8 9]
Insert 3 into a:  [0 1 2 3 7 4 5 6 7 8 9]

Original a array: [0 1 2 3 4 5 6 7 8 9]
Append 10 into a: [ 0  1  2  3  4  5  6  7  8  9 10]

Original a array:    [0 1 2 3 4 5 6 7 8 9]
Concatenate a and b: [0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9]

Original a array: [0 1 2 3 4 5 6 7 8 9]
Stack a and b:    [[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]

Original a array: [0 1 2 3 4 5 6 7 8 9]
Delete 4 from a:  [0 1 2 3 5 6 7 8 9]



Another important aspect of NumPy arrays is in their use in >1D arrays. NumPy nd arrays can be made by using commands like stack(), demonstrated in the previous cell, or reshape(), shown below. The dimensions of an nd NumPy array can be obtained with .shape(), and the number of elements in any NumPy array can be obtained with .size().

In [700]:
# Reshape a into a NumPy array with 2 rows and 5 columns
a_2d = np.reshape(a, [2,5])
print("2D array: " + str(a_2d))
print("Shape of Array: " + str(np.shape(a_2d)))
print("Number of Elements: " + str(np.size(a_2d)))

2D array: [[0 1 2 3 4]
 [5 6 7 8 9]]
Shape of Array: (2, 5)
Number of Elements: 10


You can also access elements of an nd NumPy array similar to how you would access elements of any array. More examples of indexing NumPy arrays can be found at https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.indexing.html.

In [701]:
# Retrieve the element of the array in the 0th row in column 3
print("Row 0, column 3: " + str(a_2d[0][3]))

# Retrieve all of row 1
print("Row 1: " + str(a_2d[1][:]))

# Retrieve all column 2 of all rows
print("Column 2: " + str(a_2d[:,2]))

Row 0, column 3: 3
Row 1: [5 6 7 8 9]
Column 2: [2 7]


N-dimensional NumPy arrays can also be flattened into 1D arrays using flatten().

In [702]:
# Flatten a 2D array
a_flat = a_2d.flatten()
print(a_flat)

[0 1 2 3 4 5 6 7 8 9]


## Loops
The syntax of for and while loops is shown below.

In [703]:
# For loop to create a list with 100 elements
for_loop = []
for i in range(0, 100):
    for_loop.append(i)
print("Fill list with for loop: " + str(for_loop))
print()

# While loop to remove elements from a list until it's empty
while(len(for_loop) > 0):
    del for_loop[len(for_loop)-1]
    
print("Empty list with while loop: " + str(for_loop))

Fill list with for loop: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]

Empty list with while loop: []
